### ISSUE TITLE
IndexError while scrolling and moving between subreddits

### ISSUE THREAD

**Issue by xmonraz** [michael-lazar/rtv#101]
Didn't have a chance to figure this out myself. I was scrolling through a page and when I wanted to move out, I got the exception. 

```
Connecting...
Traceback (most recent call last):
  File "/home/xavier/code/rtvtest/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/__main__.py", line 135, in <module>
    sys.exit(main())
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/__main__.py", line 118, in main
    page.loop()
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/subreddit.py", line 43, in loop
    self.draw()
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/page.py", line 405, in draw
    self._add_cursor()
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/page.py", line 471, in _add_cursor
    self._edit_cursor(curses.A_REVERSE)
  File "/home/xavier/code/rtvtest/local/lib/python2.7/site-packages/rtv/page.py", line 495, in _edit_cursor
    window, attr = self._subwindows[self.nav.cursor_index]
IndexError: list index out of range
```

I've tried to recreate it without success. 

```
In [2]: rtv.__version__
Out[2]: '1.3'
```

**Comment by michael-lazar** [comment]
Thanks for the heads up! I recently discovered a similar bug (same stack trace). I found that the problem was resizing the terminal window to be smaller, which was in some cases pushing the cursor off of the screen and out-of-bounds. There is a fix for this in b375fb71e7f34cd67be080ff0db7e1daa4ce184c, hopefully this fixes whatever you saw too!
