### ISSUE TITLE
IndexError: list index out of range when hiding comments?

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#105]
Was hiding comments (to easily view the next top level comment) and came across this:

Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.0a4', 'console_scripts', 'rtv')()
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/main.py", line 83, in main
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/subreddit.py", line 49, in loop
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/subreddit.py", line 110, in open_submission
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/submission.py", line 47, in loop
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/page.py", line 144, in draw
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/page.py", line 119, in add_cursor
  File "build/bdist.macosx-10.10-x86_64/egg/rtv/page.py", line 223, in _edit_cursor
IndexError: list index out of range
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by mekhami** [comment]
I hadn't updated in a while so I did that, haven't encountered this one yet. will re-open if it happens again.
