### ISSUE TITLE
Upvoting/Downvoting (accidentally) on a Load More item crashes:

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#108]
➜  ~  rtv -u mekhami
Connecting...
Password for mekhami:
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/rtv/__main__.py", line 135, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/rtv/__main__.py", line 118, in main
    page.loop()
  File "/usr/local/lib/python2.7/site-packages/rtv/subreddit.py", line 45, in loop
    self.controller.trigger(cmd)
  File "/usr/local/lib/python2.7/site-packages/rtv/page.py", line 176, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rtv/subreddit.py", line 96, in open_submission
    page.loop()
  File "/usr/local/lib/python2.7/site-packages/rtv/submission.py", line 46, in loop
    self.controller.trigger(cmd)
  File "/usr/local/lib/python2.7/site-packages/rtv/page.py", line 176, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rtv/page.py", line 255, in downvote
    if data['likes'] is False:
KeyError: 'likes'

Should catch this error and fail silently rather than just exiting.

**Comment by mekhami** [comment]
Looks like this actually only happens when downvoting?

**Comment by michael-lazar** [comment]
Yup good catch, it was missing an ``elif``. Fixed in https://github.com/michael-lazar/rtv/commit/3b964a7721462c6db160466e3df979a940a0c104, thanks!
