### ISSUE TITLE
Traceback error on start

### ISSUE THREAD

**Issue by Igglybuff** [michael-lazar/rtv#113]
Possibly just missing a dependency somehow, although I can't figure out which one. Happens when installed via git clone as well as via pip install. 
```
Connecting...
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.4', 'console_scripts', 'rtv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "build/bdist.linux-x86_64/egg/rtv/__main__.py", line 135, in <module>
  File "build/bdist.linux-x86_64/egg/rtv/__main__.py", line 111, in main
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 88, in wrapped
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 1321, in login
    self.request_json(self.config['login'], data=data)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 170, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 569, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 413, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 383, in handle_redirect
    timeout=timeout, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 147, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 57, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 102, in request
    allow_redirects=False)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

**Comment by michael-lazar** [comment]
Hi, thanks for the bug report. I haven't seen this particular error, but there have been some problems lately with PRAW and SSL in python 2.7. I would suggest that you try uninstalling and reinstalling from your cloned repo using python 3 instead.

**Comment by Igglybuff** [comment]
Hi, thanks for the quick response. Reinstalling with python3 fixed the problem. Cheers!
