### ISSUE TITLE
Invalid subreddit

### ISSUE THREAD

**Issue by dominicglenn** [michael-lazar/rtv#118]
The following error occurs when trying to access a non-existent sub-reddit:

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/Library/Python/2.7/site-packages/rtv/__main__.py", line 138, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/rtv/__main__.py", line 118, in main
    page.loop()
  File "/Library/Python/2.7/site-packages/rtv/subreddit.py", line 49, in loop
    self.controller.trigger(cmd)
  File "/Library/Python/2.7/site-packages/rtv/page.py", line 225, in trigger
    return func(self.instance, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rtv/subreddit.py", line 92, in prompt_subreddit
    self.refresh_content(name=name)
  File "/Library/Python/2.7/site-packages/rtv/subreddit.py", line 58, in refresh_content
    self.reddit, name, self.loader)
  File "/Library/Python/2.7/site-packages/rtv/content.py", line 313, in from_name
    return cls(display_name, submissions, loader)
  File "/Library/Python/2.7/site-packages/rtv/content.py", line 258, in __init__
    self.get(0)
  File "/Library/Python/2.7/site-packages/rtv/content.py", line 327, in get
    submission = next(self._submissions)
  File "/Library/Python/2.7/site-packages/praw/__init__.py", line 524, in get_content
    page_data = self.request_json(url, params=params)
  File "/Library/Python/2.7/site-packages/praw/decorators.py", line 173, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/praw/__init__.py", line 579, in request_json
    retry_on_error=retry_on_error)
  File "/Library/Python/2.7/site-packages/praw/__init__.py", line 423, in _request
    response = handle_redirect()
  File "/Library/Python/2.7/site-packages/praw/__init__.py", line 397, in handle_redirect
    url = _raise_redirect_exceptions(response)
  File "/Library/Python/2.7/site-packages/praw/internal.py", line 178, in _raise_redirect_exceptions
    .format(subreddit))
praw.errors.InvalidSubreddit: `lkjasdlfkjlsadkjf` is not a valid subreddit
```

**Comment by michael-lazar** [comment]
See #119, same issue
