### ISSUE TITLE
No module named '_curses'

### ISSUE THREAD

**Issue by LorenzLeitner** [michael-lazar/rtv#122]
After installing via pip starting rtv results in the following error:

````
$ ./rtv.exe
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\rtv.exe\__main__.py", line 5, in <module>
  File "C:\Python34\lib\site-packages\rtv\__main__.py", line 14, in <module>
    from .curses_helpers import curses_session
  File "C:\Python34\lib\site-packages\rtv\curses_helpers.py", line 4, in <module>
    import curses
  File "C:\Python34\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
`````

This happens with both a pip Python 2.7 and Python 3.4. (Hence the weird `./rtv.exe` start in the error log, with Python 2.7 I just used `rtv`.

OS: Windows 7 Cygwin 64
Ncurses in Cygwin is installed. I might need to install another curses module?

**Comment by michael-lazar** [comment]
Hi. I'm not familiar with how Cygwin works but it definitely looks like Python can't find your curses installation. You should be able to open a python session do

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _curses
>>> _curses
<module '_curses' from '/usr/lib/python2.7/lib-dynload/_curses.x86_64-linux-gnu.so'>
```
Although for you I'm guessing that path will be different.

**Comment by LorenzLeitner** [comment]
Thanks for the fast response!

This resulted in the same error though.

I actually was using my Windows Python installation, I now installed rtv using my Cygwin Python installation, in which _curses is included. (`Import _curses` worked)

However, now I get the following error:
````
$ rtv                                                                                       
Connecting...                                                                               
Traceback (most recent call last):                                                          
  File "/usr/bin/rtv", line 7, in <module>                                                  
    from rtv.__main__ import main                                                           
  File "/usr/lib/python2.7/site-packages/rtv/__main__.py", line 138, in <module>            
    sys.exit(main())                                                                        
  File "/usr/lib/python2.7/site-packages/rtv/__main__.py", line 112, in main                
    with curses_session() as stdscr:                                                        
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__                            
    return self.gen.next()                                                                  
  File "/usr/lib/python2.7/site-packages/rtv/curses_helpers.py", line 358, in curses_session
    curses.curs_set(0)                                                                      
_curses.error: curs_set() returned ERR                                                      
````

I read in another issue that you recommend installing it with Python 3.4, is this something I should try as well?

**Comment by LorenzLeitner** [comment]
According to [this](http://linux.die.net/man/3/curs_set) and other discussions, it has to do with the terminal. I was using ConEmu when the error occurred, using rtv with the standard Cygwin terminal works.

![image](https://cloud.githubusercontent.com/assets/9076894/8925405/bede21fa-3507-11e5-868d-a864285e4ffd.png)

**Comment by michael-lazar** [comment]
Glad you were able to figure it out :+1:
