### ISSUE TITLE
crash when opening a non existant subreddit on 1.4.1 , 1.4.0

### ISSUE THREAD

**Issue by yoshi314** [michael-lazar/rtv#124]
Example : try to open r/rtv 

<pre>
Traceback (most recent call last):
  File "/usr/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/lib/python3.4/site-packages/rtv/__main__.py", line 135, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/rtv/__main__.py", line 118, in main
    page.loop()
  File "/usr/lib/python3.4/site-packages/rtv/subreddit.py", line 51, in loop
    self.controller.trigger(cmd)
  File "/usr/lib/python3.4/site-packages/rtv/page.py", line 224, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/rtv/subreddit.py", line 94, in prompt_subreddit
    self.refresh_content(name=name)
  File "/usr/lib/python3.4/site-packages/rtv/subreddit.py", line 60, in refresh_content
    self.reddit, name, self.loader)
  File "/usr/lib/python3.4/site-packages/rtv/content.py", line 313, in from_name
    return cls(display_name, submissions, loader)
  File "/usr/lib/python3.4/site-packages/rtv/content.py", line 258, in __init__
    self.get(0)
  File "/usr/lib/python3.4/site-packages/rtv/content.py", line 327, in get
    submission = next(self._submissions)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 524, in get_content
    page_data = self.request_json(url, params=params)
  File "/usr/lib/python3.4/site-packages/praw/decorators.py", line 173, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 579, in request_json
    retry_on_error=retry_on_error)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 424, in _request
    _raise_response_exceptions(response)
  File "/usr/lib/python3.4/site-packages/praw/internal.py", line 196, in _raise_response_exceptions
    raise Forbidden(_raw=response)
praw.errors.Forbidden
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.186.23', 59879), raddr=('198.41.209.143', 443)>
/usr/lib64/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
</pre>

rtv (1.4.0)  (also affects 1.4.1)
praw (3.1.0) , both installed as root, using as typical user.

**Comment by michael-lazar** [comment]
Hi yoshi, thanks for the bug report. This has been fixed on the master branch, see https://github.com/michael-lazar/rtv/issues/119. Will be included in the 1.4.2 release which I will try to put out this weekend.
