### ISSUE TITLE
Connection timeout on start

### ISSUE THREAD

**Issue by clauseggers** [michael-lazar/rtv#152]
Starting rtv I get:
Connecting...
Connection timeout

I installed on OpenSUSE Tumbleweed using pip.

Starting rtv with a log yields:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.reddit.com
WARNING:py.warnings:/usr/lib/python3.4/site-packages/rtv/__main__.py:122: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.68', 35078), raddr=('198.41.208.143', 443)>
  print('Connection timeout')
```

**Comment by michael-lazar** [comment]
Hi! Sorry for the late reply, I would like to get to the bottom of this. Could I start by asking which version of rtv you're using? You should be able to do
```
pip show rtv
```

**Comment by clauseggers** [comment]
I get this:
```
---
Metadata-Version: 2.0
Name: rtv
Version: 1.5
Summary: A simple terminal viewer for Reddit (Reddit Terminal Viewer)
Home-page: https://github.com/michael-lazar/rtv
Author: Michael Lazar
Author-email: lazar.michael22@gmail.com
License: MIT
Location: /usr/lib/python3.4/site-packages
Requires: requests, praw, six, kitchen
```

**Comment by michael-lazar** [comment]
Ok cool, it looks like you have the latest version. Correct me if I'm wrong but it looks like you're using your system python installation. My first guess is that your python-requests is acting funky or is sticking to an older, incompatible version. My second guess is that it may be some masked SSL issue. 

Try upgrading via pip and paste the log
```
pip install -U rtv
pip install -U requests
```

**Comment by clauseggers** [comment]
Then I get:
```
pip install -U rtv
Requirement already up-to-date: rtv in /usr/lib/python3.4/site-packages
Collecting requests (from rtv)
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 617kB/s 
Requirement already up-to-date: kitchen in /usr/lib/python3.4/site-packages (from rtv)
Requirement already up-to-date: praw>=3.1.0 in /usr/lib/python3.4/site-packages (from rtv)
Collecting six (from rtv)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting decorator>=3.4.2 (from praw>=3.1.0->rtv)
  Downloading decorator-4.0.4-py2.py3-none-any.whl
Requirement already up-to-date: update-checker>=0.11 in /usr/lib/python3.4/site-packages (from praw>=3.1.0->rtv)
Installing collected packages: requests, six, decorator
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst' -> '/tmp/pip-dv2am2i1-uninstall/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib/python3.4/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/lib/python3.4/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python3.4/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python3.4/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/lib/python3.4/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/lib64/python3.4/shutil.py", line 536, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst'
```

and

```
pip install -U requests
Collecting requests
  Using cached requests-2.8.1-py2.py3-none-any.whl
Installing collected packages: requests
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst' -> '/tmp/pip-vn67ynzz-uninstall/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib/python3.4/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/lib/python3.4/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python3.4/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python3.4/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/lib/python3.4/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/lib64/python3.4/shutil.py", line 536, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/requests-2.7.0.dist-info/DESCRIPTION.rst'
```

**Comment by michael-lazar** [comment]
Hmm that's not what I expected to see but it looks like your running requests-2.7 so that should be up-to-date enough :) If you don't mind, could you quickly add the following line to the rtv launch script and try re-launching rtv? That should force it to re-throw the HTTP error so we can see the source of the problem.

**/usr/lib/python3.4/site-packages/rtv/__main__.py**
```
@@ -120,6 +120,7 @@
         print('Invalid password for username: {}'.format(args.username))
     except requests.ConnectionError:
         print('Connection timeout')
+        raise
     except requests.HTTPError:
         print('HTTP Error: 404 Not Found')
     except SubmissionError as e:
```

**Comment by clauseggers** [comment]
Sure, on which line exactly should I place the code?

**Comment by michael-lazar** [comment]
Looks like the same problem that you posted here https://github.com/untitaker/vdirsyncer/issues/224. A fix in requests https://github.com/kennethreitz/requests/issues/2659 is pending as of 2 weeks ago.

**Comment by clauseggers** [comment]
Ahh, good. A fix has been made so I (and other users) are just waiting for the fix to reach us down-stream.

Thanks for your time!

**Comment by michael-lazar** [comment]
glad I could help
