### ISSUE TITLE
rtv  is crashing after Login

### ISSUE THREAD

**Issue by THS-on** [michael-lazar/rtv#159]
After I logged in with my reddit account, I saw the message "Welcome USER" and after that the program closes with message: 
``` ConnectionError: ('Connection aborted.', ResponseNotReady()) ```

The log:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.reddit.com
WARNING:py.warnings:/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v1/access_token/ HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): oauth.reddit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v1/me.json HTTP/1.1" 200 None
ERROR:rtv.__main__:('Connection aborted.', ResponseNotReady())
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.6-py2.7.egg/rtv/__main__.py", line 77, in main
    page = SubredditPage(stdscr, reddit, oauth, subreddit)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.6-py2.7.egg/rtv/subreddit.py", line 42, in __init__
    content = SubredditContent.from_name(reddit, name, self.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.6-py2.7.egg/rtv/content.py", line 363, in from_name
    return cls(display_name, submissions, loader, order=order)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.6-py2.7.egg/rtv/content.py", line 302, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.6-py2.7.egg/rtv/content.py", line 377, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 557, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 612, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 444, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 425, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 148, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 57, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 103, in request
    allow_redirects=False, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady()) 

THS-on (sorry for my bad English)

**Comment by michael-lazar** [comment]
Hi THS-on, thanks for the detailed bug report. This is most likely an SSL issue with your version of python. I would try uninstalling rtv and reinstalling using python3, e.g.
```
sudo pip uninstall rtv
sudo pip3 install rtv
```
If you need help with this, let me know and I would be glad to walk through it in more detail.

**Comment by THS-on** [comment]
After installing pip3 and python3.4.3, rtv is working fine. My default Python version is  2.7.6 (on Linux Mint 17.2). Please change your install instructions, so that users like me don't run in the same issue. 

THS-on

**Comment by michael-lazar** [comment]
Reopening so I don't forget to add documentation about this

**Comment by michael-lazar** [comment]
Merged!
