### ISSUE TITLE
ResponseNotReady when using oauth

### ISSUE THREAD

**Issue by sedrik** [michael-lazar/rtv#169]
I get the following crash on 1.6.1 from pip after logging in using oauth.

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.reddit.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v1/access_token/ HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): oauth.reddit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/v1/me.json HTTP/1.1" 200 None
ERROR:rtv.__main__:('Connection aborted.', ResponseNotReady())
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 77, in main
    page = SubredditPage(stdscr, reddit, oauth, subreddit)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit.py", line 42, in __init__
    content = SubredditContent.from_name(reddit, name, self.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 363, in from_name
    return cls(display_name, submissions, loader, order=order)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 302, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 377, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 557, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 612, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 444, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 425, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 148, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 57, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 103, in request
    allow_redirects=False, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady())

**Comment by sedrik** [comment]
Found the solution in #159 Sorry for the issue creation, did some google-fu before pasting but did not look into the closed issues.

**Comment by michael-lazar** [comment]
Do you mind if I ask what distro you're using? It would be nice to compile a list of known incompatibilities for the README.

**Comment by sedrik** [comment]
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"

Installing and running it using pip3 was the solution
