### ISSUE TITLE
Error on launch: "module 'praw' has no attribute 'errors'

### ISSUE THREAD

**Issue by xereeto** [michael-lazar/rtv#208]
This is what I get when I run rtv (latest version):
    
    Traceback (most recent call last):
      File "/usr/bin/rtv", line 9, in <module>
        load_entry_point('rtv==1.9.0', 'console_scripts', 'rtv')()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python3.5/site-packages/rtv-1.9.0-py3.5.egg/rtv/__main__.py", line 12, in <module>
        from .config import Config, copy_default_config
      File "/usr/lib/python3.5/site-packages/rtv-1.9.0-py3.5.egg/rtv/config.py", line 14, in <module>
        from .objects import KeyMap
      File "/usr/lib/python3.5/site-packages/rtv-1.9.0-py3.5.egg/rtv/objects.py", line 78, in <module>
        class LoadScreen(object):
      File "/usr/lib/python3.5/site-packages/rtv-1.9.0-py3.5.egg/rtv/objects.py", line 119, in LoadScreen
        (praw.errors.OAuthException, 'Not logged in'),
    AttributeError: module 'praw' has no attribute 'errors'

It then exits with status 1. This happens no matter what command line flags I use.

**Comment by michael-lazar** [comment]
Hi! I'm going to take a guess here and say that you're using the praw 4.0 beta version instead of the official praw 3.4. You can check by typing
```bash
$ pip show paw
---
Name: praw
Version: 3.4.0
Location: /usr/bin/python
Requires: update-checker, decorator, requests, six
```
If it says something like 4.0.0b1, you need to downgrade with
```
$ pip install -I praw=3.4.0
```

**Comment by xereeto** [comment]
I ran

    # pip uninstall praw && pip install -i praw==3.4.0

Which fixed it for me. Thanks, and btw this project is awesome.

**Comment by michael-lazar** [comment]
Thanks :p I'm going to leave this issue open to remind me to change setup.py to require praw==3.X.X

**Comment by BlitzKraft** [comment]
I faced this issue. However, this only happens if I invoke rtv directly. This does not happen if I use `python -m rtv` or even `python3 -m rtv`. I know this is due to the mismatched praw version, but I don't understand why that does not run into the same error.

**Comment by michael-lazar** [comment]
@BlitzKraft Try running 

``$ which rtv``

and look at the shebang at the top of the file, it should tell you which python runtime is being invoked.

**Comment by BlitzKraft** [comment]
Currently it is `#!/usr/bin/python3.4`. 

I changed it to `#!/usr/bin/env python` and it's working fine, but not with python3.
