### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by magmu** [michael-lazar/rtv#219]
I keep getting the following when attempting to launch:

Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.9.0', 'console_scripts', 'rtv')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.2/dist-packages/rtv/__main__.py", line 127, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.2/dist-packages/rtv/__main__.py", line 108, in main
    page.loop()
  File "/usr/local/lib/python3.2/dist-packages/rtv/page.py", line 67, in loop
    self.draw()
  File "/usr/local/lib/python3.2/dist-packages/rtv/page.py", line 260, in draw
    self._draw_header()
  File "/usr/local/lib/python3.2/dist-packages/rtv/page.py", line 278, in _draw_header
    self.term.add_line(window, sub_name, 0, 0)
  File "/usr/local/lib/python3.2/dist-packages/rtv/terminal.py", line 251, in add_line
    window.addstr(row, col, text, *params)
TypeError: must be str, not bytes

Any ideas?

**Comment by michael-lazar** [comment]
Hi, I'm sorry that you're having problems!

It looks like you're using python 3.2. That version of python has some annoying unicode problems and as such is not supported by rtv and some of its dependencies (https://github.com/praw-dev/praw/pull/532). If you have python 2.7 on your system I would suggest trying that instead. If that's not an option, you will need to install python 3.3+

**Comment by magmu** [comment]
And that would do it, my apologies.
