### ISSUE TITLE
"// ENTER" crashes rtv

### ISSUE THREAD

**Issue by octomagon** [michael-lazar/rtv#224]
Typing "//" then pressing ENTER crashes rtv consistently.
(searching for the subreddit '/', which would be silly)

OS X 10.11.5
Python 2.7.10
rtv 1.9.0

```
Traceback (most recent call last):
  File "/usr/local/Cellar/rtv/1.9.0/libexec/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.9.0', 'console_scripts', 'rtv')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2709, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2369, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/__main__.py", line 127, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/__main__.py", line 108, in main
    page.loop()
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/page.py", line 69, in loop
    self.controller.trigger(ch)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/objects.py", line 571, in trigger
    return func(self.instance, *args, **kwargs) if func else None
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/subreddit.py", line 73, in prompt_subreddit
    self.refresh_content(order='ignore', name=name)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/subreddit.py", line 47, in refresh_content
    self.reddit, name, self.term.loader, order=order)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/lib/python3.5/site-packages/rtv/content.py", line 407, in from_name
    subreddit = reddit.get_subreddit(name)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/vendor/lib/python3.5/site-packages/praw/__init__.py", line 1078, in get_subreddit
    return objects.Subreddit(self, subreddit_name, *args, **kwargs)
  File "/usr/local/Cellar/rtv/1.9.0/libexec/vendor/lib/python3.5/site-packages/praw/objects.py", line 1518, in __init__
    subreddit_name = json_dict['url'].split('/')[2]
TypeError: 'NoneType' object is not subscriptable
```

Thanks for the great app!!

**Comment by michael-lazar** [comment]
Confirmed, thanks for the bug report. Should be an easy fix.
