### ISSUE TITLE
Handle x-post better

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#239]
Right now only x-post that are links to a self post are handled properly. Sometimes a x-post is a link to a subreddit or other reddit page.

**Comment by michael-lazar** [comment]
Could you post an example?

**Comment by woorst** [comment]
Got to `/r/TinySubredditoftheDay` and try to open any link.

**Comment by michael-lazar** [comment]
Thanks, confirmed bug.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/rtv/__main__.py", line 132, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/rtv/__main__.py", line 113, in main
    page.loop()
  File "/usr/local/lib/python3.4/dist-packages/rtv/page.py", line 69, in loop
    self.controller.trigger(ch)
  File "/usr/local/lib/python3.4/dist-packages/rtv/objects.py", line 581, in trigger
    return func(self.instance, *args, **kwargs) if func else None
  File "/usr/local/lib/python3.4/dist-packages/rtv/subreddit.py", line 103, in open_link
    self.open_submission(url=data['url_full'])
  File "/usr/local/lib/python3.4/dist-packages/rtv/subreddit.py", line 86, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/local/lib/python3.4/dist-packages/rtv/submission.py", line 24, in __init__
    self.content = SubmissionContent.from_url(reddit, url, term.loader)
  File "/usr/local/lib/python3.4/dist-packages/rtv/content.py", line 261, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 1062, in get_submission
    params=params)
  File "<decorator-gen-197>", line 2, in from_url
  File "/usr/local/lib/python3.4/dist-packages/praw/decorators.py", line 271, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/objects.py", line 1117, in from_url
    submission = Submission.from_json(response)
  File "/usr/local/lib/python3.4/dist-packages/praw/objects.py", line 1078, in from_json
    submission = json_response[0]['data']['children'][0]
KeyError: 0
```
