### ISSUE TITLE
Invalid username / password exception not handled

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#24]
Trying to start with an invalid username or password raises the following exception
```
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    main()
  File "main.py", line 83, in main
    reddit.login(args.username, args.password)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 1330, in login
    self.request_json(self.config['login'], data=data)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.InvalidUserPass: `wrong password` on field `passwd`
```
This should be caught and handled inside of main.py, similar to how subreddit name is being done. There should be a concise error message that includes the username and starred out password e.g. `civilization_phaze_3:********`

**Comment by shanhind** [comment]
I'm going to fix this tomorrow.

**Comment by michael-lazar** [comment]
Fixed by shanhind
