### ISSUE TITLE
AUR: pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by binaryplease** [michael-lazar/rtv#258]
Running the latest version from AUR on arch linux.
rtv crashes instantly on start.

This is the console output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (praw 3.4.0 (/usr/lib/python3.5/site-packages), Requirement.parse('praw==3.5.0'), {'rtv'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rtv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2928, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2914, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2941, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'praw==3.5.0' distribution was not found and is required by rtv

```

**Comment by michael-lazar** [comment]
Pinging @shaggytwodope, he's the guy who maintains the AUR package.

**Comment by shaggytwodope** [comment]
@binaryplease hi there, I've changed to the praw-git package from the default praw in community. This fixes a issue thats not yet released. If you can try removing rtv and reinstalling. This should force any depend changes. There might be better ways to do this but not fully away at this moment lol. Also there are two packages, are you using rtv-git or just the rtv package? Any issues after reinstalling just hit me up here or email from my profile. Remember to close the issue once it's solved.

**Comment by binaryplease** [comment]
I cant build the dependencies. This error occurs:

```
Making package: python-praw-git 3.1.0.r1126.g0ae0d9d-1 (Mo 25. Jul 15:36:02 CEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning python-praw-git git repo...
Cloning into bare repository '/tmp/yaourt-tmp-binaryplease/aur-python-praw-git/python-praw-git'...
remote: Counting objects: 12866, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 12866 (delta 81), reused 0 (delta 0), pack-reused 12700
Receiving objects: 100% (12866/12866), 21.77 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (8651/8651), done.
Checking connectivity... done.
==> Validating source files with sha256sums...
    python-praw-git ... Skipped
==> Extracting sources...
  -> Creating working copy of praw git repo...
Cloning into 'python-praw-git'...
done.
==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: from .const import __version__  # NOQA.r1578.gdce26a7
==> ERROR: Makepkg was unable to build .
==> Restart building python-praw-git ? [y/N]
==> ----------------------------------------
==> 

```


Also a lot of the dependency-packages are orphaned

**Comment by Hund** [comment]
I believe I have the same issue. I'm running Arch Linux and just installed `rtv` from AUR.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (update-checker 0.12 (/usr/lib/python3.5/site-packages), Requirement.parse('update_checker==0.11'), {'praw'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rtv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2989, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 675, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'update_checker==0.11' distribution was not found and is required by praw
```

**Comment by Hund** [comment]
A workaround for this issue until a proper solution is:

> Changing "update_checker ==0.11" to "update_checker >=0.11" in /usr/lib/python3.5/site-packages/praw-3.5.0-py3.5.egg-info/requires.txt works around the problem.

I found the tip amongst the comments here: https://aur.archlinux.org/packages/rtv.

**Comment by michael-lazar** [comment]
Thanks, I'm going to add a note to the README to let people know
