### ISSUE TITLE
Unable to open after installing, due to 'version conflict' error.

### ISSUE THREAD

**Issue by TenTypesOfPeople** [michael-lazar/rtv#321]
This is the result of running 'rtv' in the terminal:

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six==1.10'))
```

**Comment by shaggytwodope** [comment]
@TenTypesOfPeople It'd be extremely useful to know how you installed and on what target os/distro.

**Comment by TenTypesOfPeople** [comment]
oh gosh, my bad! I'm using a Debian Jessie, and I installed it by cloning and the setup, iirc. (not using pip)

**Comment by shaggytwodope** [comment]
@TenTypesOfPeople ahhh, well the issue is simple. See that six wants 1.10 and you only have 1.8.

**Comment by michael-lazar** [comment]
What shaggy said, try running

```
sudo apt-get install python-pip
sudo pip install six -U
```

**Comment by TenTypesOfPeople** [comment]
Thanks! That worked.

Unfortunately, another issue popped up. Here's the traceback after I tried to run rtv.

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.13.0', 'console_scripts', 'rtv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/__main__.py", line 137, in main
    page = SubredditPage(reddit, term, config, oauth, name)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/subreddit_page.py", line 33, in __init__
    self.content = SubredditContent.from_name(reddit, name, term.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/content.py", line 430, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv-1.13.0-py2.7.egg/rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 567, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 116, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 622, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 453, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 434, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 146, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 102, in request
    allow_redirects=False, verify=verify)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 855, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

**Comment by michael-lazar** [comment]
I apologize for never responding. I think that you need to update your OpenSSL libraries as described [here](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package/29099439#29099439). Feel free to re-open the issue if you try that and it still doesn't work.
