### ISSUE TITLE
Crashes when resizing window

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#322]
I've seen this error message a few times now. It appears when I get stuck waiting for a page to load i.e.
```
requesting...
```
and I try to resize the terminal window.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/michael/Projects/rtv_project/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/home/michael/Projects/rtv_project/rtv/__main__.py", line 152, in main
    page.loop()
  File "rtv/page.py", line 89, in loop
    self.controller.trigger(ch)
  File "rtv/objects.py", line 383, in trigger
    return func(self.instance, *args, **kwargs)
  File "rtv/subreddit_page.py", line 77, in prompt_subreddit
    self.refresh_content(order='ignore', name=name)
  File "rtv/subreddit_page.py", line 51, in refresh_content
    self.reddit, name, self.term.loader, order=order)
  File "rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "rtv/content.py", line 430, in __init__
    self.get(0)
  File "rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 567, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 116, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 622, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 453, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 434, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 146, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 102, in request
    allow_redirects=False, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 207, in recv
    [self.socket], [], [], self.socket.gettimeout())
select.error: (4, 'Interrupted system call')
```

**Comment by michael-lazar** [comment]
I have been unable to reliably reproduce this. It might be tied to a particular requests/urllib3 version.
