### ISSUE TITLE
[Bug] AttributeError: 'Session' object has no attribute 'merge_environment_settings'

### ISSUE THREAD

**Issue by ProfessionalNihilist** [michael-lazar/rtv#325]
Installed on Ubuntu trusty via `pip`.

````
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 137, in main
    page = SubredditPage(reddit, term, config, oauth, name)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit_page.py", line 33, in __init__
    self.content = SubredditContent.from_name(reddit, name, term.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 430, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 565, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 620, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 451, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 432, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 150, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 101, in request
    settings = self.http.merge_environment_settings(
AttributeError: 'Session' object has no attribute 'merge_environment_settings'
````

**Comment by michael-lazar** [comment]
Thanks for the report. I will look into it, but for now you could try installing the python3 version instead and see if that works.

**Comment by deadcyclo** [comment]
I'm getting the same issue on the python3 version:

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python3.4/dist-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/rtv/__main__.py", line 137, in main
    page = SubredditPage(reddit, term, config, oauth, name)
  File "/usr/local/lib/python3.4/dist-packages/rtv/subreddit_page.py", line 33, in __init__
    self.content = SubredditContent.from_name(reddit, name, term.loader)
  File "/usr/local/lib/python3.4/dist-packages/rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "/usr/local/lib/python3.4/dist-packages/rtv/content.py", line 430, in __init__
    self.get(0)
  File "/usr/local/lib/python3.4/dist-packages/rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 565, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python3.4/dist-packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 620, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 451, in _request
    response = handle_redirect()
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 432, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/handlers.py", line 150, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/handlers.py", line 101, in request
    settings = self.http.merge_environment_settings(
AttributeError: 'Session' object has no attribute 'merge_environment_settings'
```

**Comment by John2143** [comment]
I'm also getting this error
```
Chromebook ~ 
$ pip -V                                                                                          ⬡ - [Fri  5:35 AM]
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
                                                                                                                     
Chromebook ~ 
$ python --version                                                                                ⬡ - [Fri  5:35 AM]
Python 2.7.6
                                                                                                                     
Chromebook ~ 
$ python3 --version                                                                               ⬡ - [Fri  5:35 AM]
Python 3.4.3
                                                                                                                     
Chromebook ~ 
$ rtv -V                                                                                          ⬡ - [Fri  5:35 AM]
rtv 1.14.1
                                                                                                                     
Chromebook ~ 
$ rtv                                                                                             ⬡ - [Fri  5:35 AM]
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 137, in main
    page = SubredditPage(reddit, term, config, oauth, name)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit_page.py", line 33, in __init__
    self.content = SubredditContent.from_name(reddit, name, term.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 430, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 565, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 620, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 451, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 432, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 150, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/handlers.py", line 101, in request
    settings = self.http.merge_environment_settings(
AttributeError: 'Session' object has no attribute 'merge_environment_settings'
```

**Comment by michael-lazar** [comment]
I was able to replicate the issue, it looks like all you need to do to fix it is to update your requests library to something >= v3.4.0. I'll update the project requirements to reflect this. In the meantime you can run

```
sudo pip install -U requests
```

or equivalent and that should fix it.
