### ISSUE TITLE
[Bug] Error when running after fresh install "ValueError: unknown locale: UTF-8"

### ISSUE THREAD

**Issue by jeromefaria** [michael-lazar/rtv#339]
I am getting the following error after a fresh install:

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rtv/__main__.py", line 107, in main
    encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

Here are some details of my system: 
```
macOS 10.12.2 (16C67)
Python 2.7.10
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
```

**Comment by michael-lazar** [comment]
It looks like you're actually running on python 3.6.0. That might be the issue? I haven't tested on 3.6 yet.

**Comment by shaggytwodope** [comment]
Might need to manually set locale for your shell.

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

You can add these to your .profile or .bash_profile etc.

**Comment by jeromefaria** [comment]
Thanks @shaggytwodope, that fixed it!
