### ISSUE TITLE
Crash when trying to view saved comment.

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#369]
From the saved posts list I can view saved submission but rtv crash when I try to view a saved comment.
```
Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.13.0', 'console_scripts', 'rtv')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 152, in main
    page.loop()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 78, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3.6/site-packages/rtv/objects.py", line 591, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rtv/subreddit_page.py", line 126, in open_link
    self.open_submission()
  File "/usr/lib/python3.6/site-packages/rtv/subreddit_page.py", line 103, in open_submission
    url = data['permalink']
KeyError: 'permalink'
```

**Comment by michael-lazar** [comment]
Thanks for creating the issue, it looks like an oversight that should be fairly easy to fix.
