### ISSUE TITLE
TypeError: subreddit_name must be a non-empty string.

### ISSUE THREAD

**Issue by jarandaf** [michael-lazar/rtv#375]
I am getting the following error with the brew-installed package right after authorizing the application with reddit:

```python
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.15.1', 'console_scripts', 'rtv')()
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 178, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 161, in main
    page.loop()
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/page.py", line 78, in loop
    self.controller.trigger(ch)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/objects.py", line 594, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/page.py", line 246, in login
    self.oauth.authorize()
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/oauth.py", line 197, in authorize
    info = self.reddit.get_access_information(self.params['code'])
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1392, in get_access_information
    self.set_access_credentials(**retval)
  File "<decorator-gen-56>", line 2, in set_access_credentials
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 294, in require_oauth
    return function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1591, in set_access_credentials
    self.user = self.get_me()
  File "<decorator-gen-51>", line 2, in get_me
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1426, in get_me
    user = objects.Redditor(self, response['name'], response)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 882, in __init__
    fetch, info_url, **kwargs)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 70, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 179, in _populate
    setattr(self, name, value)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 117, in __setattr__
    value = Subreddit(self.reddit_session, value, fetch=False)
  File "/usr/local/Cellar/rtv/1.15.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 1602, in __init__
    raise TypeError('subreddit_name must be a non-empty string.')
TypeError: subreddit_name must be a non-empty string.
```

EDIT: Same error happens to be with pip3 version.

**Comment by michael-lazar** [comment]
Thanks for the bug report!

The error looks to be documented here: https://www.reddit.com/r/redditdev/comments/6c53y3/praw_rrefresh_access_information_returns/

This project is still on PRAW 3 so we'll need to find a work-around.

**Comment by michael-lazar** [comment]
I just pushed a fix to the praw package that this project bundles.

**Comment by jarandaf** [comment]
Thanks @michael-lazar for the bug fix, it works :-)
