### ISSUE TITLE
ImportError: No module named BaseHTTPServer (Mac OS 10.12)

### ISSUE THREAD

**Issue by sealevelcain** [michael-lazar/rtv#391]
Apologies if this is an error that has already been solved - I did search but was unable to find anything. I'm new to unix/command line/etc so I do apologise if I'm missing something. 

Using Terminal/zsh, upon typing `rtv --help ` I get this error: 

Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rtv/__main__.py", line 30, in <module>
    from .oauth import OAuthHelper
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rtv/oauth.py", line 14, in <module>
    from six.moves.BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
ImportError: No module named BaseHTTPServer

**Comment by sealevelcain** [comment]
My mistake. I had installed via pip and brew, so uninstalled both then re-installed with brew only and it worked.
