### ISSUE TITLE
'Shift + J' and 'Shift + K' closes program immediately

### ISSUE THREAD

**Issue by Pro-Prietary** [michael-lazar/rtv#407]
Log file

> 2017-08-04 12:54:30,083:INFO:__main__.py:105:Starting new session, RTV v1.17.0
2017-08-04 12:54:30,084:INFO:__main__.py:106:/usr/bin/python, 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
2017-08-04 12:54:30,084:INFO:__main__.py:118:Environment: [('$DISPLAY', ':0.0'), ('$TERM', 'xterm-256color'), ('$XDG_CONFIG_HOME', None), ('$RTV_EDITOR', None), ('$RTV_URLVIEWER', None), ('$RTV_BROWSER', None), ('$BROWSER', None), ('$PAGER', None), ('$VISUAL', None), ('$EDITOR', None)]
2017-08-04 12:54:30,084:INFO:__main__.py:145:Using packaged PRAW distribution, commit ad0dbcf49d5937ffd39e13e45ebcb404b00c582a
2017-08-04 12:54:30,100:DEBUG:connectionpool.py:818:Starting new HTTPS connection (1): api.reddit.com
2017-08-04 12:54:30,387:DEBUG:connectionpool.py:395:https://api.reddit.com:443 "POST /api/v1/access_token/ HTTP/1.1" 200 214
2017-08-04 12:54:32,102:DEBUG:connectionpool.py:818:Starting new HTTPS connection (1): oauth.reddit.com
2017-08-04 12:54:32,379:DEBUG:connectionpool.py:395:https://oauth.reddit.com:443 "GET /api/v1/me.json HTTP/1.1" 200 1007
2017-08-04 12:54:35,435:DEBUG:connectionpool.py:395:https://oauth.reddit.com:443 "GET /.json?limit=1024 HTTP/1.1" 200 65145
2017-08-04 12:54:37,899:ERROR:__main__.py:194:'level'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 188, in main
    page.loop()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3.6/site-packages/rtv/objects.py", line 594, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rtv/submission_page.py", line 212, in move_sibling_next
    level = self.content.get(cursor)['level']
KeyError: 'level'

**Comment by michael-lazar** [comment]
Thanks, it looks like there was a typo in the latest release. I just fixed it here 41a2be30e1dc23c2ea59df034e31346a8a8a83f1, will publish a new bugfix release this evening

**Comment by michael-lazar** [comment]
Fixed in v1.17.1
