### ISSUE TITLE
NameError: name 'mailcap' is not defined

### ISSUE THREAD

**Issue by k4k** [michael-lazar/rtv#449]
This is the error received on Fedora 26 after installing rtv from the Fedora repository:

```
Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.14.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 124, in main
    term = Terminal(stdscr, config)
  File "/usr/lib/python3.6/site-packages/rtv/terminal.py", line 55, in __init__
    self._mailcap_dict = mailcap.getcaps()
NameError: name 'mailcap' is not defined
```
```
$ rpm -q rtv
rtv-1.14.1-2.fc26.noarch
```

**Comment by shaggytwodope** [comment]
Is mailcap Installed?, This is not an rtv, you need to hit up the packager for rtv on fedora if installing mailcap does not solve.

**Comment by k4k** [comment]
```
$ rpm -q mailcap
mailcap-2.1.48-1.fc26.noarch
```
I'll attempt to contact the package maintainer to see if they can assist if there's nothing further to troubleshoot from the rtv side.

**Comment by michael-lazar** [comment]
Since the fedora package has been broken for so long without any indication of updating, I removed it as an installation method from the README.
