### ISSUE TITLE
use_default_colors() returned ERR

### ISSUE THREAD

**Issue by michaelachrisco** [michael-lazar/rtv#452]
Running on Ubuntu 17.04 via python3 -m rtv:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mesamunefire/rtv/rtv/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/home/mesamunefire/rtv/rtv/__main__.py", line 172, in main
    with curses_session() as stdscr:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/mesamunefire/rtv/rtv/objects.py", line 96, in curses_session
    curses.use_default_colors()
_curses.error: use_default_colors() returned ERR
```

**Comment by michael-lazar** [comment]
Thanks, could you please try running with logging enabled and paste the log file here:

```
python3 -m rtv --log  rtv.log
```

**Comment by michaelachrisco** [comment]
Here is rtv.log

```
2017-10-11 23:25:22,257:INFO:__main__.py:105:Starting new session, RTV v1.17.1
2017-10-11 23:25:22,258:INFO:__main__.py:106:/usr/bin/python3, 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118]
2017-10-11 23:25:22,258:INFO:__main__.py:118:Environment: [('$DISPLAY', None), ('$TERM', 'vt220'), ('$XDG_CONFIG_HOME',
None), ('$RTV_EDITOR', None), ('$RTV_URLVIEWER', None), ('$RTV_BROWSER', None), ('$BROWSER', None), ('$PAGER', None), ('
$VISUAL', None), ('$EDITOR', None)]
2017-10-11 23:25:22,258:INFO:__main__.py:145:Using packaged PRAW distribution, commit ad0dbcf49d5937ffd39e13e45ebcb404b0
0c582a
2017-10-11 23:25:22,259:WARNING:objects.py:66:Curses failed to initialize the cursor mode
2017-10-11 23:25:22,260:ERROR:__main__.py:194:use_default_colors() returned ERR
Traceback (most recent call last):
  File "/home/mesamunefire/rtv/rtv/__main__.py", line 154, in main
    with curses_session() as stdscr:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/mesamunefire/rtv/rtv/objects.py", line 69, in curses_session
    curses.use_default_colors()
_curses.error: use_default_colors() returned ERR
```

**Comment by michael-lazar** [comment]
My guess is that it's failing because of ```('$TERM', 'vt220')```. Are you trying to use some obscure terminal emulator?

Either way, this should be pretty easy to fix in the code by wrapping the offending line in a ``try...except...`` block. This looks like a valid bug since the application should still be able to run on terminals that don't support color.

**Comment by michaelachrisco** [comment]
Yes that is what it turned out to be. Other terminals work fine. I would have thought `rtv --monochrome` would fix the issue but it still gives the same error. Thanks!
