### ISSUE TITLE
rtv aborts when searching

### ISSUE THREAD

**Issue by tekstrong** [michael-lazar/rtv#460]
Steps:  Open rtv, load subreddit, press 'f' to search, enter search term and hit enter. rtv aborts and outputs the following (this is under Ubuntu 17.04):

`Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.14.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 152, in main
    page.loop()
  File "/usr/lib/python3/dist-packages/rtv/page.py", line 78, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3/dist-packages/rtv/objects.py", line 595, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rtv/subreddit_page.py", line 67, in search_subreddit
    self.reddit, name, self.term.loader, query=query)
  File "/usr/lib/python3/dist-packages/rtv/content.py", line 584, in from_name
    return cls(display_name, submissions, loader, order=display_order)
  File "/usr/lib/python3/dist-packages/rtv/content.py", line 430, in __init__
    self.get(0)
  File "/usr/lib/python3/dist-packages/rtv/content.py", line 605, in get
    submission = next(self._submissions)
  File "/usr/lib/python3/dist-packages/praw/__init__.py", line 1161, in search
    url = self.config['search'] % subreddit
TypeError: not all arguments converted during string formatting`

**Comment by michael-lazar** [comment]
Hello, thanks for the bug report. Since you're using an older version of RTV, try installing ``v1.18.0`` through **pip** and see if that fixes it.

**Comment by tekstrong** [comment]
My apologies... it appears that at some point I had installed rtv from my package manager. I removed that and used the current version and all is well - closing.
