### ISSUE TITLE
_curses.error: addstr() returned ERR

### ISSUE THREAD

**Issue by dave-gg** [michael-lazar/rtv#461]
python: 3.6.3
rtv: 1.18.0

```
Traceback (most recent call last):
  File "/home/dave/.pyenv/versions/3.6.3/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/__main__.py", line 221, in <module>
    sys.exit(main())
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/__main__.py", line 204, in main
    page.loop()
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/objects.py", line 621, in trigger
    return func(self.instance, *args, **kwargs)
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/subreddit_page.py", line 140, in open_submission
    page.loop()
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/page.py", line 81, in loop
    self.draw()
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/page.py", line 377, in draw
    self._draw_content()
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/page.py", line 498, in _draw_content
    attr = self._draw_item(subwindow, data, subwin_inverted)
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/submission_page.py", line 270, in _draw_item
    return self._draw_comment(win, data, inverted)
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/submission_page.py", line 325, in _draw_comment
    self.term.add_line(win, text, row, 1)
  File "/home/dave/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rtv/terminal.py", line 279, in add_line
    window.addstr(row, col, text, *params)
_curses.error: addstr() returned ERR
```

I was scrolling down comments (with my mouse wheel) and had this happen.

**Comment by dave-gg** [comment]
Looks like this may have been fixed here:
https://github.com/michael-lazar/rtv/commit/a8c4b1adf477beda6c133d7c4feaeccbca0d4aee#diff-3819e52ace59e781870267ce9ff22e4e

but hasn't made it into the latest in pip yet.

**Comment by michael-lazar** [comment]
The commit that you referenced has now been released into pip. Please re-open if you still see this bug, but I agree with you that it was probably fixed.
