### ISSUE TITLE
Crashes when showing comments

### ISSUE THREAD

**Issue by PortableStick** [michael-lazar/rtv#464]
I just installed rtv for the first time.  I can open the app, log in, and browse subreddits just fine.  When I press `l` to view comments, rtv crashes.

Installed via Homebrew
macOS 10.12.6
iTerm3 & Terminal.app
zsh
Tmux (crashes without tmux as well)

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.18.0', 'console_scripts', 'rtv')()
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 221, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 204, in main
    page.loop()
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/objects.py", line 621, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/subreddit_page.py", line 136, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/submission_page.py", line 31, in __init__
    max_comment_cols=config['max_comment_cols'])
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/content.py", line 344, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1107, in get_submission
    params=params)
  File "<decorator-gen-199>", line 2, in from_url
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 1155, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 629, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 487, in _json_reddit_objecter
    return object_class.from_api_response(self, json_data['data'])
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 55, in from_api_response
    return cls(reddit_session, json_dict=json_dict)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 637, in __init__
    underscore_names=['replies'])
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 70, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 179, in _populate
    setattr(self, name, value)
  File "/usr/local/Cellar/rtv/1.18.0/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 127, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

Please let me know if there's any other info I can get for you.

**Comment by tylnesh** [comment]
Same here on Ubuntu MATE 17.10. I tried using both python2 and python3.

**Comment by jmsundar** [comment]
See #462

**Comment by T-jw** [comment]
Try upgrading to version 1.19.0.

**Comment by michael-lazar** [comment]
I'm going to re-open 462, please continue any discussion there
