### ISSUE TITLE
rtv crashes when trying to view a text post

### ISSUE THREAD

**Issue by heyitswither** [michael-lazar/rtv#518]
```
$ uname -a
Linux tinydebian 4.9.0-6-686-pae #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) i686 GNU/Linux
```

```
$ rtv --version
rtv 1.14.1
```

```
# Stacktrace
Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.14.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 169, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 152, in main
    page.loop()
  File "/usr/lib/python3/dist-packages/rtv/page.py", line 78, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3/dist-packages/rtv/objects.py", line 595, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rtv/subreddit_page.py", line 126, in open_link
    self.open_submission()
  File "/usr/lib/python3/dist-packages/rtv/subreddit_page.py", line 107, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/lib/python3/dist-packages/rtv/submission_page.py", line 30, in __init__
    max_comment_cols=config['max_comment_cols'])
  File "/usr/lib/python3/dist-packages/rtv/content.py", line 321, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/lib/python3/dist-packages/praw/__init__.py", line 1042, in get_submission
    params=params)
  File "<decorator-gen-191>", line 2, in from_url
  File "/usr/lib/python3/dist-packages/praw/decorators.py", line 268, in wrap
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 1111, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/lib/python3/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/praw/__init__.py", line 621, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/lib/python3/dist-packages/praw/__init__.py", line 479, in _json_reddit_objecter
    return object_class.from_api_response(self, json_data['data'])
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 56, in from_api_response
    return cls(reddit_session, json_dict=json_dict)
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 613, in __init__
    underscore_names=['replies'])
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 71, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 171, in _populate
    setattr(self, name, value)
  File "/usr/lib/python3/dist-packages/praw/objects.py", line 119, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

This seems to happen with any text post, but [here](https://reddit.com/r/AskReddit/comments/8042i7) is the one in particular that didn't work for me.

**Comment by pjrulez** [comment]
Funny, stopping by, just installed via apt (brand new user) on _Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux_ with same version or rtv.  Could login and browse a little but it simply exits with this (EXACT!!!) error. Hope it's just some initial misconfigutation...

Basically pressing right arrow or l for comments causes it.

**Comment by michael-lazar** [comment]
Reddit recently made a change in their API, which is causing this crash in older versions of RTV.

To fix it, all you need to do is upgrade to the latest version of RTV. If it hasn't been pushed to the debian repo yet, you will need to install using pip.

**Comment by pjrulez** [comment]
Thank you. It works.
sudo apt remove rtv
pip3 install rtv
found it in $HOME/.local/rtv so I added it to $PATH
(feeling genius) :dancing_men: 
Sorry, should have checked repology link from readme. It's clear it's marked with red. I'm a bit sad stable (too) often means not up to date...

**Comment by michael-lazar** [comment]
Glad that it worked!
