### ISSUE TITLE
crashes after opening specific post with special characters

### ISSUE THREAD

**Issue by CoffeeVector** [michael-lazar/rtv#530]
I opened this post
https://www.reddit.com/r/calculus/comments/87d6m6/can_someone_help_me_understand_how_to_do_the/
It's' math related, so I guess it's because it's got funny characters

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.22.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 252, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 234, in main
    page.loop()
  File "/usr/local/lib/python2.7/dist-packages/rtv/page.py", line 82, in loop
    self.controller.trigger(ch)
  File "/usr/local/lib/python2.7/dist-packages/rtv/objects.py", line 591, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit_page.py", line 195, in open_link
    self.open_submission()
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit_page.py", line 178, in open_submission
    page.loop()
  File "/usr/local/lib/python2.7/dist-packages/rtv/page.py", line 80, in loop
    self.draw()
  File "/usr/local/lib/python2.7/dist-packages/rtv/page.py", line 365, in draw
    self._draw_content()
  File "/usr/local/lib/python2.7/dist-packages/rtv/page.py", line 521, in _draw_content
    self._draw_item(win, data, inverted)
  File "/usr/local/lib/python2.7/dist-packages/rtv/submission_page.py", line 296, in _draw_item
    return self._draw_submission(win, data)
  File "/usr/local/lib/python2.7/dist-packages/rtv/submission_page.py", line 431, in _draw_submission
    self.term.add_line(win, text, row, 1, attr=attr)
  File "/usr/local/lib/python2.7/dist-packages/rtv/terminal.py", line 277, in add_line
    window.addstr(row, col, text, *params)
TypeError: int,int,str,attr
```

**Comment by michael-lazar** [comment]
Thanks for the bug report and stack trace 👍  The characters in that post look like a weird edge case, but nevertheless the application shouldn't be crashing outright like that.

**Comment by michael-lazar** [comment]
Looks like the same issue as described here: https://github.com/wifiphisher/wifiphisher/issues/506
