### ISSUE TITLE
Installation help wanted

### ISSUE THREAD

**Issue by dackdel** [michael-lazar/rtv#532]
Trying to install it on windows that runs ubuntu through hyper.io

What sort of error is this?

`Exception:
Traceback (most recent call last):
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in insta
ll
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move
_wheel_files
    isolated=self.isolated,
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_file
s
    clobber(source, lib_dir, True)
  File "/home/dackdel/.local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/decorator.py'`

**Comment by michael-lazar** [comment]
It's a permission error. You need to either install as root

```
sudo pip install rtv
```

or install rtv in your user directory

```
pip instal rtv --user
```

**Comment by dackdel** [comment]
Thank you that worked.
