### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by Ifnister** [michael-lazar/rtv#534]
I was in the middle of the comments of [this post](https://www.reddit.com/r/AskReddit/comments/8ahj0a/whats_a_pointless_fact_you_know/) and rtv crashed after pressing "j". I opened rtv again, went to the same post, went down in the comments and it crashed again, very likely in the same place.
This is the error message:
```
Traceback (most recent call last):
  File "/usr/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 252, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/rtv/__main__.py", line 234, in main
    page.loop()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 82, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3.6/site-packages/rtv/objects.py", line 591, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rtv/subreddit_page.py", line 196, in open_link
    self.open_submission()
  File "/usr/lib/python3.6/site-packages/rtv/subreddit_page.py", line 179, in open_submission
    page.loop()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 80, in loop
    self.draw()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 365, in draw
    self._draw_content()
  File "/usr/lib/python3.6/site-packages/rtv/page.py", line 518, in _draw_content
    self._draw_item(win, data, inverted)
  File "/usr/lib/python3.6/site-packages/rtv/submission_page.py", line 294, in _draw_item
    return self._draw_comment(win, data, inverted)
  File "/usr/lib/python3.6/site-packages/rtv/submission_page.py", line 362, in _draw_comment
    self.term.add_line(win, text, row, 1, attr=attr)
  File "/usr/lib/python3.6/site-packages/rtv/terminal.py", line 277, in add_line
    window.addstr(row, col, text, *params)
ValueError: embedded null byte
```
I'm on Arch Linux and rtv was installed through pip. Version: 1.22.1

**Comment by michael-lazar** [comment]
Thanks for the bug report, I was able to reproduce the error.

**Comment by Ifnister** [comment]
Thank you for your work
