### ISSUE TITLE
Login with custom $RTV_BROWSER

### ISSUE THREAD

**Issue by sprnza** [michael-lazar/rtv#584]
Hi there!
I'd like to use rtv on my headless server. So I set $RTV_BROWSER and $BROWSER to `w3m` and with those set I can't launch rtv. It returns this error:

```
srvr ➜  ~ rtv
Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.23.0', 'console_scripts', 'rtv')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 476, in
load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/rtv/__main__.py", line 254, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/rtv/__main__.py", line 168, in main
    patch_webbrowser()
  File "/usr/lib/python3.7/site-packages/rtv/objects.py", line 37, in patch_webbrowser
    webbrowser.register('surf', None, webbrowser.BackgroundBrowser('surf'))
  File "/usr/lib/python3.7/webbrowser.py", line 26, in register
    register_standard_browsers()
  File "/usr/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by michael-lazar** [comment]
Thanks for the report, this is a new bug in python 3.7 (the method signature was changed). I still need to run through the test suite in 3.7 to sift out changes like these.
