### ISSUE TITLE
Update to python 3.7 breaks rtv TypeError: register() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by sevaho** [michael-lazar/rtv#588]
I upgrade to python 3.7 on Arch and now rtv is broken.

```
Traceback (most recent call last):
  File "/usr/sbin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/lib/python3.7/site-packages/rtv/__main__.py", line 254, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/rtv/__main__.py", line 168, in main
    patch_webbrowser()
  File "/usr/lib/python3.7/site-packages/rtv/objects.py", line 37, in patch_webbrowser
    webbrowser.register('surf', None, webbrowser.BackgroundBrowser('surf'))
  File "/usr/lib/python3.7/webbrowser.py", line 26, in register
    register_standard_browsers()
  File "/usr/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by michael-lazar** [comment]
Thanks for reporting the issue, this is a duplicate of https://github.com/michael-lazar/rtv/issues/584. I'll look into it ASAP because this is probably going to effect a large number of users.

**Comment by michael-lazar** [comment]
An issue was filed in python's bug tracker here: [31014](https://bugs.python.org/issue31014). A pull request has been merged upstream, but I will see if I can apply a patch for RTV in the meantime. 

https://github.com/python/cpython/pull/7267
