### ISSUE TITLE
Crash when hitting G on empty thread

### ISSUE THREAD

**Issue by gbpi** [michael-lazar/rtv#695]
If the thread has 1 or comments, G works as expected. With 0 comments it always produces a crash for me.

```
rtv version: rtv 1.26.0
rtv module path: /usr/lib/python3.7/site-packages/rtv/__main__.py
python version: 3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
python executable: /usr/bin/python
praw version: packaged, commit 1656ec224e57
locale, encoding: en_US.UTF-8, UTF-8
Environment Variables
  BROWSER         : 
  DISPLAY         : :0
  EDITOR          : vim
  LANG            : en_US.UTF-8
  PAGER           : less
  RTV_BROWSER     : qutebrowser
  RTV_EDITOR      : 
  RTV_PAGER       : 
  RTV_URLVIEWER   : 
  TERM            : xterm-256color
  VISUAL          : 
  XDG_CONFIG_HOME : 
  XDG_DATA_HOME   : 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rtv/__main__.py", line 255, in main
    page = page.loop()
  File "/usr/lib/python3.7/site-packages/rtv/page.py", line 97, in loop
    self.handle_selected_page()
  File "/usr/lib/python3.7/site-packages/rtv/subreddit_page.py", line 43, in handle_selected_page
    self.selected_page = self.selected_page.loop()
  File "/usr/lib/python3.7/site-packages/rtv/page.py", line 92, in loop
    self.draw()
  File "/usr/lib/python3.7/site-packages/rtv/page.py", line 663, in draw
    self._draw_content()
  File "/usr/lib/python3.7/site-packages/rtv/page.py", line 825, in _draw_content
    self.nav.flip((len(self._subwindows) - 1))
  File "/usr/lib/python3.7/site-packages/rtv/objects.py", line 503, in flip
    assert n_windows >= 0
AssertionError

rtv has crashed. Please report this traceback at:
https://github.com/michael-lazar/rtv/issues

```

**Comment by ajakk** [comment]
Hello, I've created a fork of rtv on Gitlab. I've just [pushed a commit](https://gitlab.com/ajak/rtv/tree/dev) to my dev branch there that should fix this bug.
