### ISSUE TITLE
When pressing < o > key on a reddit post rtv crashes, "Can't pickle local object"

### ISSUE THREAD

**Issue by lilyvM8** [michael-lazar/rtv#712]
**Describe the bug**
open rtv, scroll down a few posts, press the <o> key to open a post (not sure if that's the actual key to open a post). rtv closes, I get a stack trace and your github account.
`AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'`

**Describe your environment**
`Traceback (most recent call last):
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/__main__.py", line 223, in main
    url = requests.head(
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'update': No schema supplied. Perhaps you meant http://update?

rtv has crashed. Please report this traceback at:`

- Mojave 10.14.6 installed through homebrew, rtv had just been installed before I opened the program.)

**Comment by michael-lazar** [comment]
https://github.com/michael-lazar/rtv/issues/710
