### ISSUE TITLE
Crash while trying to sign in

### ISSUE THREAD

**Issue by loquatdonut** [michael-lazar/rtv#713]
Greetings!
Macbook7.1 Mavericks 10.9.5
Installed rtv using brew and got this error while trying to sign in account (immediately after pressing 'U')

rtv version: rtv 1.27.0
rtv module path: /usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/__main__.py
python version: 3.8.1 (default, Jan 26 2020, 04:50:57)  [Clang 6.0 (clang-600.0.57)]
python executable: /usr/local/Cellar/rtv/1.27.0_1/libexec/bin/python3.8
praw version: packaged, commit 1656ec224e57
locale, encoding: ru_RU.UTF-8, UTF-8
Environment Variables
  BROWSER         :
  DISPLAY         :
  EDITOR          :
  LANG            : ru_RU.UTF-8
  PAGER           :
  RTV_BROWSER     : firefox
  RTV_EDITOR      :
  RTV_PAGER       :
  RTV_URLVIEWER   :
  TERM            : xterm-256color
  VISUAL          :
  XDG_CONFIG_HOME :
  XDG_DATA_HOME   :

Traceback (most recent call last):
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/__main__.py", line 255, in main
    page = page.loop()
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/page.py", line 94, in loop
    self.controller.trigger(ch)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/objects.py", line 604, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/page.py", line 319, in login
    self.oauth.authorize()
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/oauth.py", line 190, in authorize
    self.term.open_browser(authorize_url)
  File "/usr/local/Cellar/rtv/1.27.0_1/libexec/lib/python3.8/site-packages/rtv/terminal.py", line 615, in open_browser
    p.start()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'

rtv has crashed. Please report this traceback at:
https://github.com/michael-lazar/rtv/issues

**Comment by michael-lazar** [comment]
https://github.com/michael-lazar/rtv/issues/710
