### ISSUE TITLE
App crashes when trying to visit banned subreddits

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#80]
I know this is a far-edge case, but I think the app should handle this.

Full trace:
```
Traceback (most recent call last):
  File "~/py3env/lib/python3.4/site-packages/rtv/content.py", line 240, in __init__
    self.get(0)
  File "~/py3env/lib/python3.4/site-packages/rtv/content.py", line 309, in get
    submission = next(self._submissions)
  File "~/py3env/lib/python3.4/site-packages/praw/__init__.py", line 508, in get_content
    page_data = self.request_json(url, params=params)
  File "~/py3env/lib/python3.4/site-packages/praw/decorators.py", line 163, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "~/py3env/lib/python3.4/site-packages/praw/__init__.py", line 561, in request_json
    retry_on_error=retry_on_error)
  File "~/py3env/lib/python3.4/site-packages/praw/__init__.py", line 403, in _request
    _raise_response_exceptions(response)
  File "~/py3env/lib/python3.4/site-packages/praw/internal.py", line 178, in _raise_response_exceptions
    response.raise_for_status()
  File "~/py3env/lib/python3.4/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/py3env/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "~/py3env/lib/python3.4/site-packages/rtv/__main__.py", line 133, in <module>
    sys.exit(main())
  File "~/py3env/lib/python3.4/site-packages/rtv/__main__.py", line 116, in main
    page.loop()
  File "~/py3env/lib/python3.4/site-packages/rtv/subreddit.py", line 45, in loop
    self.controller.trigger(cmd)
  File "~/py3env/lib/python3.4/site-packages/rtv/page.py", line 140, in trigger
    return func(self.instance, *args, **kwargs)
  File "~/py3env/lib/python3.4/site-packages/rtv/subreddit.py", line 88, in prompt_subreddit
    self.refresh_content(name=name)
  File "~/py3env/lib/python3.4/site-packages/rtv/subreddit.py", line 54, in refresh_content
    self.reddit, name, self.loader)
  File "~/py3env/lib/python3.4/site-packages/rtv/content.py", line 295, in from_name
    return cls(display_name, submissions, loader)
  File "~/py3env/lib/python3.4/site-packages/rtv/content.py", line 243, in __init__
    raise SubredditError(display_name)
NameError: name 'display_name' is not defined
```

**Comment by michael-lazar** [comment]
Whoops I made a typo, see aa91c18a2512d9c1961db0707eb7ea17b0a1e6b9
Since I pooped the bed with v1.2, I just upped the version to v1.2.1

**Comment by Brobin** [comment]
Sweet, just pulled it and didn't receive the error again.

**Comment by yskmt** [comment]
I just got this error with version 1.4.2. Can you guys verify it?

**Comment by michael-lazar** [comment]
Can confirm, the error message is different though -

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 138, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rtv/__main__.py", line 118, in main
    page.loop()
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit.py", line 49, in loop
    self.controller.trigger(cmd)
  File "/usr/local/lib/python2.7/dist-packages/rtv/page.py", line 225, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit.py", line 92, in prompt_subreddit
    self.refresh_content(name=name)
  File "/usr/local/lib/python2.7/dist-packages/rtv/subreddit.py", line 58, in refresh_content
    self.reddit, name, self.loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 314, in from_name
    return cls(display_name, submissions, loader)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 258, in __init__
    self.get(0)
  File "/usr/local/lib/python2.7/dist-packages/rtv/content.py", line 328, in get
    submission = next(self._submissions)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 524, in get_content
    page_data = self.request_json(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 173, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 579, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 424, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 198, in _raise_response_exceptions
    raise NotFound(_raw=response)
praw.errors.NotFound
```

It looks like in PRAW 3 they switched from `requests.HTTPError` to `praw.errors.NotFound`. The try-except block in **content.py** catches the former but not the latter. It's kind of annoying that they broke so many of the exceptions, but the fix should be easy.
