### ISSUE TITLE
Getting an error when trying to open rtv

### ISSUE THREAD

**Issue by tobywhughes** [michael-lazar/rtv#84]
I will type rtv into the terminal and get this:

      Traceback (most recent call last):
    File "/usr/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.2.1', 'console_scripts', 'rtv')()
    File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 522, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
    File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2647, in load_entry_point
    return ep.load()
    File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2320, in load
    return self.resolve()
    File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2326, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
    File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
    File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/__main__.py", line 133, in <module>
    File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/__main__.py", line 115, in main
    File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/subreddit.py", line 36, in __init__
    File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/content.py", line 248, in from_name AttributeError: 'NoneType' object has no attribute 'strip'

So it looks like it is not loading with any default subreddit for me. I created a .cfg file manually in ~/.config/rtv and it works. Was this something that was supposed to happen automatically? If it was, I guess the error is that mine wasn't. If it isn't, a more intuitive, automatic way should be added.

**Comment by michael-lazar** [comment]
You're correct, the program should load the front page by default if no config file is specified. This was a pretty bad oversight. Just fixed in 348e25e, I'll update the pip version tonight.
