### ISSUE TITLE
Unexpected redirect

### ISSUE THREAD

**Issue by Thimoteus** [michael-lazar/rtv#85]
```
$ rtv
Connecting...
Traceback (most recent call last):
  File "/usr/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.2.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/__main__.py", line 133, in <module>
  File "/usr/lib/python3.4/site-packages/rtv-1.2.1-py3.4.egg/rtv/__main__.py", line 110, in main
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 1334, in login
    self.user = self.get_redditor(user)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 949, in get_redditor
    return objects.Redditor(self, user_name, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/praw/objects.py", line 746, in __init__
    fetch, info_url)
  File "/usr/lib/python3.4/site-packages/praw/objects.py", line 73, in __init__
    self.has_fetched = self._populate(json_dict, fetch)
  File "/usr/lib/python3.4/site-packages/praw/objects.py", line 133, in _populate
    json_dict = self._get_json_dict() if fetch else {}
  File "/usr/lib/python3.4/site-packages/praw/objects.py", line 126, in _get_json_dict
    as_objects=False)
  File "/usr/lib/python3.4/site-packages/praw/decorators.py", line 163, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 561, in request_json
    retry_on_error=retry_on_error)
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 402, in _request
    response = handle_redirect()
  File "/usr/lib/python3.4/site-packages/praw/__init__.py", line 376, in handle_redirect
    url = _raise_redirect_exceptions(response)
  File "/usr/lib/python3.4/site-packages/praw/internal.py", line 164, in _raise_redirect_exceptions
    raise RedirectException(response.url, new_url)
praw.errors.RedirectException: Unexpected redirect from http://www.reddit.com/user/Thimoteus/about/.json to https://www.reddit.com/user/Thimoteus/about/.json
```

I got this error when I installed via `sudo pip install rtv` and by `sudo python setup.py install`.

**Comment by Brobin** [comment]
What is your default subreddit set as in `rtv.cfg`?

**Comment by Thimoteus** [comment]
I have `subreddit=linux` in my rtv.cfg.

**Comment by Brobin** [comment]
It looks like this is an issue on login. Is your user/pass correct?

**Comment by Thimoteus** [comment]
Yes, I use [pass](http://www.passwordstore.org/) to manage passwords, so I just pasted it in.

**Comment by michael-lazar** [comment]
Hi,
What version of praw are you running? Are you using any custom configuration settings for praw? (http://praw.readthedocs.org/en/latest/pages/configuration_files.html#configuration-variables)

**Comment by Thimoteus** [comment]
Here's the output of `pip show praw`:
```
---
Metadata-Version: 2.0
Name: praw
Version: 2.1.21
Summary: PRAW, an acronym for `Python Reddit API Wrapper`, is a python package that allows for simple access to reddit's API.
Home-page: http://praw.readthedocs.org/
Author: Bryce Boe
Author-email: bbzbryce@gmail.com
License: GPLv3
Location: /usr/lib/python3.4/site-packages
Requires: requests, update-checker, six
```
And [here's](https://gist.github.com/Thimoteus/58263458df78a1ce953a) my `praw.ini`. AFAIK it's the same as [this one](https://github.com/praw-dev/praw/blob/master/praw/praw.ini).

**Comment by larryhynes** [comment]
I've just ran into the same issue. After confirming that `https://www.reddit.com/user/lhynes/about/.json` does actually exist, I deleted lines 163 and 164 in `../python2.7/site-packages/praw/internal.py`, i.e. delete

```python
    elif not RE_RANDOM.search(response.url):
        raise RedirectException(response.url, new_url)
```
and now rtv launches fine, if that's of any use to anyone trying to track this down.

**Comment by michael-lazar** [comment]
@larryhynes Thanks for the heads up! This is definitely sounding like a PRAW issue. It looks like PRAW is trying to hit `http:` instead of `https` to get user information and reddit is redirecting to the secure url. I encourage you to post an issue on [praw-dev](https://github.com/praw-dev/praw/issues) if you want to follow up on this.

**Comment by larryhynes** [comment]
A recent commit message on the praw github is titled 'enforce https everywhere', so if I had to guess they've introduced a redirect that isn't being handled well. I might post an issue there.

**Comment by michael-lazar** [comment]
Closing because this is really a PRAW bug and a fix is upcoming.
