### ISSUE TITLE
Crash on https redirect on login

### ISSUE THREAD

**Issue by Demorde** [michael-lazar/rtv#89]
When logging into a reddit account that has https enabled the client can't handle the http -> https redirect and crashes.
---
$ rtv
Connecting...
Traceback (most recent call last):
  File "/usr/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/lib/python2.7/site-packages/rtv/__main__.py", line 134, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/rtv/__main__.py", line 110, in main
    reddit.login(args.username, args.password)
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 1334, in login
    self.user = self.get_redditor(user)
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 949, in get_redditor
    return objects.Redditor(self, user_name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/praw/objects.py", line 746, in __init__
    fetch, info_url)
  File "/usr/lib/python2.7/site-packages/praw/objects.py", line 73, in __init__
    self.has_fetched = self._populate(json_dict, fetch)
  File "/usr/lib/python2.7/site-packages/praw/objects.py", line 133, in _populate
    json_dict = self._get_json_dict() if fetch else {}
  File "/usr/lib/python2.7/site-packages/praw/objects.py", line 126, in _get_json_dict
    as_objects=False)
  File "/usr/lib/python2.7/site-packages/praw/decorators.py", line 163, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 561, in request_json
    retry_on_error=retry_on_error)
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 402, in _request
    response = handle_redirect()
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 376, in handle_redirect
    url = _raise_redirect_exceptions(response)
  File "/usr/lib/python2.7/site-packages/praw/internal.py", line 164, in _raise_redirect_exceptions
    raise RedirectException(response.url, new_url)
praw.errors.RedirectException: Unexpected redirect from http://www.reddit.com/user/USERNAME/about/.json to https://www.reddit.com/user/USERNAME/about/.json

**Comment by michael-lazar** [comment]
Hi, thanks for the bug report! This is a know issue, see https://github.com/michael-lazar/rtv/issues/85 for more info.
